### ISSUE TITLE
bmatsuo/go-lexer is missing

### ISSUE THREAD

**Issue by guildencrantz** [bmatsuo/go-jsontree#1]
It looks like you've got a functional jsonpath library implemented here, but unfurtunately it imports bmatsuo/go-lexer (in exp/jsonpath/lexer/lexer.go), which can no longer be found. Has this package been moved, or is there a drop-in replacement available?

**Comment by bmatsuo** [comment]
Sorry. I must have never pushed that package. It is basically the lexer described in Rob Pike's talk, [Lexical Scanning in Go](http://blog.golang.org/two-go-talks-lexical-scanning-in-go-and).

Anyway, I've pushed the package. Be warned that there are no tests for it.

I can't speak too much to the quality of the jsonpath library. I don't remember the exact state. I think the Selectors work relatively well. But the parser is far from complete. Please feel free to work on it and open pull requests.

**Comment by bmatsuo** [comment]
Oh yea. The jsonpath tests also had a broken dependency >_<

You'll need to pull and `go get github.com/bmatsuo/yup`
